# Generated by Django 2.2.16 on 2022-08-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_review_author',
        ),
    ]
